#!/bin/bash

# Test script for TCP Chat with new features
# This script demonstrates the new features added to the chat server

echo "=== TCP-Chat Feature Demo ==="
echo ""
echo "Server is running on localhost:8888"
echo ""
echo "You can test the following new features:"
echo ""
echo "1. /help - Display all available commands"
echo "   Example: /help"
echo ""
echo "2. /users - List all users in the current room"
echo "   Example: /users"
echo ""
echo "3. /dm <username> <message> - Send private messages"
echo "   Example: /dm alice Hello from Bob!"
echo ""
echo "4. /status <status> - Set your status"
echo "   Example: /status away"
echo ""
echo "Original Features:"
echo "  - /nick <name> - Set your username"
echo "  - /join <room> - Join a room"
echo "  - /rooms - List all rooms"
echo "  - /msg <message> - Send message to room"
echo "  - /quit - Exit the chat"
echo ""
echo "To test the chat, open new terminals and connect with:"
echo "  telnet localhost 8888"
echo ""
echo "Example session:"
echo "  1. telnet localhost 8888"
echo "  2. /nick Alice"
echo "  3. /join general"
echo "  4. /help"
echo "  5. /users"
echo "  6. /status online"
echo "  7. /msg Hello everyone!"
echo ""
echo "Then open another terminal and:"
echo "  1. telnet localhost 8888"
echo "  2. /nick Bob"
echo "  3. /join general"
echo "  4. /dm Alice Nice to meet you!"
echo "  5. /msg Hi team!"
echo ""
